name: Publish to pub.dev

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  publish:
    # Avoid accidental publishes from forks with the same workflow.
    if: github.repository == 'milhomem/native_updater'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for authentication using OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Validate package
        run: flutter pub publish --dry-run

      - name: Publish package
        run: flutter pub publish --force
